### ISSUE TITLE
No issue here, just expressing my gratitude!

### ISSUE THREAD

**Issue by ovizii** [TessyPowder/kdenlive-vnc-docker#1]
I've used the base image of jlesage for a couple of projects but when I needed a video editor I failed countless times. 
I tried to get openshot, shotcut, flowblade and a couple of more alternatives running with this base image and utterly failed.

You just saved my bacon. I simply needed *any* video editor to run inside a container and be accessible via browser. 

Are you planning on keeping the image updated? If not please let me know and I'll build my own based on your Dockerfile and startup.sh 

Btw. your example of mounting your video sources into the container:
`/pathToFolderOnHost/':'/sharedContent`
is the folder sharedContent randomly chosen or is this a path which kdenlive "knows"? I'm asking because I usually mount my stuff into i.e. /mnt/Videos

**Comment by JonathanTreffler** [comment]
> is the folder sharedContent randomly chosen or is this a path which kdenlive "knows"? I'm asking because I usually mount my stuff into i.e. /mnt/Videos

randomly chosen :)

**Comment by ovizii** [comment]
thanks!
